Routing
1DSAG/UI5-Best-Practice pull request #57
Opened 2021-07-02 09:54 UTC by hkaintz

2021-07-14 13:35 UTC, vobu requested changes

2021-07-14 13:35 UTC, vobu commented on docs/routing/index.md
> +It is best practice to configure the routing in the descriptor file (`manifest.json`) while it is also possible to do it in the `Component.js` file or locally by calling the constructors of the class
even though technically true of course, i find the bare mention of the non-manifest options rather confusing to the reader. so IMHO i'd either elaborate on both (component, sub-classed routing) in `configuration` or similar

2021-07-14 13:35 UTC, vobu commented on docs/routing/configuration.markdown
> +nav_order: 3
I'd suggest to make this the first sub-nav item after index: config is essential before anything :)

2021-07-14 13:35 UTC, vobu commented on docs/routing/patterns.markdown
> +---
all of the route pattern items need a code exmaple IMO - it's really difficult for the reader to translate the prose to code him-/herself

2021-07-14 13:35 UTC, vobu commented on docs/routing/configuration.markdown
> +## Config
same comment as in `patterns`: this needs code example to make it "visible" for the reader what the options are all about

2021-07-14 13:35 UTC, vobu commented on docs/routing/methods.markdown
> +Navigation can be triggered by method the [navTo](https://sapui5.hana.ondemand.com/#/api/sap.ui.core.routing.Router%23methods/navTo){:target="_blank"} on `sap.ui.core.routing.Router`.
the method

2021-07-14 13:35 UTC, vobu commented on docs/routing/methods.markdown
> +Navigation can be triggered by method the [navTo](https://sapui5.hana.ondemand.com/#/api/sap.ui.core.routing.Router%23methods/navTo){:target="_blank"} on `sap.ui.core.routing.Router`.
also, try using `https://ui5.sap.com` as the documentation domain - b/c reasons, you know ... :)

2021-07-14 13:35 UTC, vobu commented on docs/routing/methods.markdown
> +You can use a generic navTo method in your BaseController and call it from any controller within your applicataion:
typo "application"

2021-07-14 13:35 UTC, vobu commented on docs/routing/methods.markdown
> +        navTo: function(sName, oParameters, oComponentTargetInfo, bReplace) {
what about ES6-ing things, à la:
```js 
sap.ui.require(..., (Controller) => {
    navTo(sName, oParameters, ...) { }
})
```
but this just a hint, not a necessity :)

2021-07-14 13:35 UTC, vobu commented on docs/routing/methods.markdown
> +The routeMatched event is fired if a pattern of any route in the routing configuration is matched.
code fence `routeMatched`

2021-07-14 13:35 UTC, vobu commented on docs/routing/methods.markdown
> +The routeMatched event is fired if a pattern of any route in the routing configuration is matched.
and: the code example shows the handler for the `patternMatched` event, not the `routeMatched`

2021-07-14 13:35 UTC, vobu commented on docs/routing/methods.markdown
> +### Matched
this is actually the `routeMatched` event, right? (see above)

2021-07-14 13:35 UTC, vobu commented on docs/routing/titles.markdown
> +Routing in SAPUI5 allows you to define titles declaratively in the configuration. The title can be set with valid binding syntax which is then resolved under the scope of the target to which it belon
supercool!

2021-12-02 11:17 UTC, hkaintz commented
@marianfoo Ich habs gerade mit git rebase versucht, hat leider nicht funktioniert. Die neuen commits haben zwar den richtigen User, aber die Alten sind immer noch da.
Ist es möglich vorübergehend den check zu disablen?

2021-12-02 11:19 UTC, hkaintz commented
I have read the CLA Document and I hereby sign the CLA

2021-12-03 08:12 UTC, marianfoo commented
> @marianfoo Ich habs gerade mit git rebase versucht, hat leider nicht funktioniert. Die neuen commits haben zwar den richtigen User, aber die Alten sind immer noch da. Ist es möglich vorübergehend den check zu disablen?

Hi @hkaintz, ja wir können für diesen Fall trotzdem mergen. Mit deinen GitHub User hast du ja unterschrieben.
@vobu ist mit dem PR alles ok?

2022-01-23 14:54 UTC, marianfoo commented
@hkaintz fixed Error with "CLA Assistant" by sqashing your commits into one

2022-06-16 07:00 UTC, merged